platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

target 'Spells' do
  pod "RealmSwift", "3.17.0"
  pod 'TPKeyboardAvoiding', '1.3.2'
  pod 'SPStorkController', '1.6.5'
  pod 'lottie-ios'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  # Firebese:
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  target 'SpellsTests' do
    inherit! :search_paths
    
  end
end
